"""Opens a GitHub PR adding the generated dashboard JSON under dashboards/, matching
this repo's existing Git-Sync-managed layout. Deploy happens automatically after a
human approves and merges, via Grafana's own Git Sync pulling from `main` (and
.github/workflows/validate-dashboards.yml / CODEOWNERS already gate the merge).
"""
from __future__ import annotations

import base64
import logging
import os
from typing import Callable
from datetime import datetime, timezone

import requests

API_ROOT = "https://api.github.com"

logger = logging.getLogger("agent.github_pr")


class GitHubPRError(RuntimeError):
    pass


def _headers() -> dict:
    token = os.environ["GITHUB_TOKEN"]
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _repo() -> str:
    return os.environ["GITHUB_REPO"]  # "owner/name"


def _request(method: str, path: str, **kwargs):
    resp = requests.request(method, f"{API_ROOT}{path}", headers=_headers(), timeout=30, **kwargs)
    if resp.status_code >= 300:
        raise GitHubPRError(f"{method} {path} failed: {resp.status_code} {resp.text}")
    return resp.json() if resp.content else {}


def get_json(path: str, **params) -> dict | list:
    return _request("GET", path, params=params or None)


def get_file_text(path: str, ref: str) -> str | None:
    """Contents of a file at a ref, or None if it doesn't exist there."""
    repo = _repo()
    resp = requests.get(
        f"{API_ROOT}/repos/{repo}/contents/{path}",
        headers=_headers(),
        params={"ref": ref},
        timeout=30,
    )
    if resp.status_code == 404:
        return None
    if resp.status_code >= 300:
        raise GitHubPRError(f"GET contents {path}@{ref} failed: {resp.status_code} {resp.text}")
    return base64.b64decode(resp.json()["content"]).decode()


def open_pr(
    *,
    branch: str,
    files: dict[str, str],
    commit_message: str,
    title: str,
    body: str | Callable[[str], str],
    labels: list[str] | None = None,
) -> dict:
    """Creates `branch` off the base branch, commits `files` (path -> content) one
    commit per file, and opens a PR. `body` may be a callable taking the last commit
    SHA (so it can be embedded in the PR description)."""
    repo = _repo()
    base_branch = os.getenv("GITHUB_BASE_BRANCH", "main")

    base_ref = _request("GET", f"/repos/{repo}/git/ref/heads/{base_branch}")
    base_sha = base_ref["object"]["sha"]
    _request("POST", f"/repos/{repo}/git/refs", json={"ref": f"refs/heads/{branch}", "sha": base_sha})

    commit_sha = base_sha
    for path, content in files.items():
        put = _request(
            "PUT",
            f"/repos/{repo}/contents/{path}",
            json={
                "message": commit_message,
                "content": base64.b64encode(content.encode()).decode(),
                "branch": branch,
            },
        )
        commit_sha = put.get("commit", {}).get("sha", commit_sha)

    pr = _request(
        "POST",
        f"/repos/{repo}/pulls",
        json={
            "title": title,
            "head": branch,
            "base": base_branch,
            "body": body(commit_sha) if callable(body) else body,
        },
    )
    if labels:
        try:  # best-effort: needs Issues/PR write; never fail the PR over a label
            _request("POST", f"/repos/{repo}/issues/{pr['number']}/labels", json={"labels": labels})
        except GitHubPRError as exc:
            logger.warning("Could not label PR #%s: %s", pr["number"], exc)

    return {"pr_url": pr["html_url"], "number": pr["number"], "branch": branch, "commit_sha": commit_sha}


def open_dashboard_pr(
    *,
    slug: str,
    partner_name: str,
    dashboard_json: str,
    request_text: str,
    lineage: dict | None = None,
) -> dict:
    """Opens the onboarding PR. With `lineage`, the PR body carries the lineage
    table, the editable spec block and the hidden marker used by outcome tracking."""
    from agent.lineage import AGENT_LABEL, render_pr_body

    path = f"dashboards/{slug}.json"
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    branch = f"onboard-{slug}-{timestamp}"

    def body(commit_sha: str) -> str:
        if lineage is None:
            return (
                f"Auto-generated by the Partner Onboarding Observability Agent.\n\n"
                f"**Request:** {request_text}\n\n"
                f"Review the dashboard JSON, then merge to deploy via Git Sync."
            )
        lineage["agent_commit_sha"] = commit_sha
        lineage["branch"] = branch
        return render_pr_body(lineage)

    return open_pr(
        branch=branch,
        files={path: dashboard_json},
        commit_message=f"Onboard {partner_name}: add monitoring dashboard",
        title=f"Onboard {partner_name}: add monitoring dashboard",
        body=body,
        labels=[AGENT_LABEL],
    )
