"""Opens a GitHub PR adding the generated dashboard JSON under dashboards/, matching
this repo's existing Git-Sync-managed layout. Deploy happens automatically after a
human approves and merges, via Grafana's own Git Sync pulling from `main` (and
.github/workflows/validate-dashboards.yml / CODEOWNERS already gate the merge).
"""
from __future__ import annotations

import base64
import os
from datetime import datetime, timezone

import requests

API_ROOT = "https://api.github.com"


class GitHubPRError(RuntimeError):
    pass


def _headers() -> dict:
    token = os.environ["GITHUB_TOKEN"]
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _repo() -> str:
    return os.environ["GITHUB_REPO"]  # "owner/name"


def _request(method: str, path: str, **kwargs) -> dict:
    resp = requests.request(method, f"{API_ROOT}{path}", headers=_headers(), timeout=30, **kwargs)
    if resp.status_code >= 300:
        raise GitHubPRError(f"{method} {path} failed: {resp.status_code} {resp.text}")
    return resp.json() if resp.content else {}


def open_dashboard_pr(*, slug: str, partner_name: str, dashboard_json: str, request_text: str) -> dict:
    repo = _repo()
    base_branch = os.getenv("GITHUB_BASE_BRANCH", "main")
    path = f"dashboards/{slug}.json"
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    branch = f"onboard-{slug}-{timestamp}"

    base_ref = _request("GET", f"/repos/{repo}/git/ref/heads/{base_branch}")
    base_sha = base_ref["object"]["sha"]

    _request(
        "POST",
        f"/repos/{repo}/git/refs",
        json={"ref": f"refs/heads/{branch}", "sha": base_sha},
    )

    _request(
        "PUT",
        f"/repos/{repo}/contents/{path}",
        json={
            "message": f"Onboard {partner_name}: add monitoring dashboard",
            "content": base64.b64encode(dashboard_json.encode()).decode(),
            "branch": branch,
        },
    )

    pr = _request(
        "POST",
        f"/repos/{repo}/pulls",
        json={
            "title": f"Onboard {partner_name}: add monitoring dashboard",
            "head": branch,
            "base": base_branch,
            "body": (
                f"Auto-generated by the Partner Onboarding Observability Agent.\n\n"
                f"**Request:** {request_text}\n\n"
                f"Review the dashboard JSON, then merge to deploy via Git Sync."
            ),
        },
    )

    return {"pr_url": pr["html_url"], "branch": branch}
