"""Lineage stamping: every agent-generated dashboard records where it came from.

The same lineage record is written to two places:

1. The dashboard JSON itself (spec.description, spec.tags, spec.links) so anyone
   looking at a live dashboard in Grafana can see the request, prompt version and
   model, and click straight through to the exact LLM call in Langfuse.
2. The PR description — a human-readable table, an *editable* spec block that
   reviewers can correct, and a machine-readable hidden marker that the GitHub
   webhook (agent/pr_outcomes.py) parses back when the PR is merged/closed.

The hidden marker is the source of truth for outcome tracking, so the webhook still
works even if the agent's local state database is lost.
"""
from __future__ import annotations

import base64
import json
import os
import re
from datetime import datetime, timezone

from agent.observability import estimate_cost_usd

LINEAGE_SCHEMA_VERSION = 1
AGENT_LABEL = "agent-generated"

_MARKER_RE = re.compile(r"<!--\s*agent-lineage:v(\d+)\s+([A-Za-z0-9+/=]+)\s*-->")
_SPEC_BLOCK_RE = re.compile(r"```json\s+agent-spec\s*\n(.*?)\n```", re.DOTALL)


def build_lineage(*, request_text: str, extraction, slug: str, dashboard_path: str) -> dict:
    """extraction is an agent.llm.spec_extractor.ExtractionResult."""
    return {
        "schema_version": LINEAGE_SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "agent_version": os.getenv("AGENT_VERSION", "dev"),
        "request_text": request_text,
        "prompt_version": extraction.prompt_version,
        "model": extraction.model,
        "fallback_used": extraction.fallback_used,
        "attempted_models": extraction.attempted_models,
        "trace_id": extraction.trace_id,
        "trace_url": extraction.trace_url,
        "slug": slug,
        "dashboard_path": dashboard_path,
        "extracted_spec": extraction.spec.model_dump(mode="json"),
        "tokens": {"prompt": extraction.prompt_tokens, "completion": extraction.completion_tokens},
        "estimated_cost_usd": estimate_cost_usd(extraction.prompt_tokens, extraction.completion_tokens),
    }


def _tag_safe(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9._:-]+", "-", value)[:50]


def stamp_dashboard(dashboard: dict, lineage: dict) -> dict:
    """Mutates and returns the dashboard with lineage in description/tags/links."""
    spec = dashboard["spec"]
    request = lineage["request_text"]
    if len(request) > 300:
        request = request[:297] + "..."
    spec["description"] = (
        f'Generated by the Partner Onboarding Agent from: "{request}" | '
        f'prompt {lineage["prompt_version"]} | model {lineage["model"]} | '
        f'trace {lineage["trace_id"]} | {lineage["generated_at"]}'
    )
    tags = list(spec.get("tags", []))
    for tag in (
        AGENT_LABEL,
        f'prompt:{_tag_safe(lineage["prompt_version"])}',
        f'model:{_tag_safe(lineage["model"])}',
    ):
        if tag not in tags:
            tags.append(tag)
    spec["tags"] = tags

    links = [link for link in spec.get("links", []) if not link.get("title", "").startswith("Langfuse trace")]
    if lineage.get("trace_url"):
        links.append(
            {
                "title": f'Langfuse trace {lineage["trace_id"][:12]}',
                "type": "link",
                "url": lineage["trace_url"],
                "icon": "external link",
                "targetBlank": True,
                "tooltip": "The exact LLM call that produced this dashboard's spec",
                "asDropdown": False,
                "includeVars": False,
                "keepTime": False,
                "tags": [],
            }
        )
    spec["links"] = links
    return dashboard


def encode_marker(lineage: dict) -> str:
    payload = base64.b64encode(json.dumps(lineage, separators=(",", ":")).encode()).decode()
    return f"<!-- agent-lineage:v{LINEAGE_SCHEMA_VERSION} {payload} -->"


def render_pr_body(lineage: dict) -> str:
    trace = (
        f'[`{lineage["trace_id"]}`]({lineage["trace_url"]})'
        if lineage.get("trace_url")
        else f'`{lineage["trace_id"]}` (Langfuse disabled)'
    )
    model = f'`{lineage["model"]}`'
    if lineage.get("fallback_used"):
        model += f' (fallback — tried {", ".join(lineage["attempted_models"])})'
    spec_json = json.dumps(lineage["extracted_spec"], indent=2)
    return (
        "Auto-generated by the Partner Onboarding Observability Agent.\n\n"
        f'**Request:** {lineage["request_text"]}\n\n'
        "### Lineage\n\n"
        "| | |\n|---|---|\n"
        f'| Prompt version | `{lineage["prompt_version"]}` |\n'
        f"| Model | {model} |\n"
        f"| Langfuse trace | {trace} |\n"
        f'| Agent version | `{lineage["agent_version"]}` |\n'
        f'| Generated at | {lineage["generated_at"]} |\n\n'
        "### Extracted spec\n\n"
        "If the agent misunderstood the request, **edit this block** to the correct spec "
        "(and/or fix the dashboard JSON). When the PR is merged or closed, your correction "
        "is turned into a candidate eval test case automatically.\n\n"
        f"```json agent-spec\n{spec_json}\n```\n\n"
        "Review the dashboard JSON, then merge to deploy via Git Sync.\n\n"
        f"{encode_marker(lineage)}\n"
    )


def parse_marker(body: str | None) -> dict | None:
    if not body:
        return None
    m = _MARKER_RE.search(body)
    if not m:
        return None
    try:
        return json.loads(base64.b64decode(m.group(2)).decode())
    except (ValueError, json.JSONDecodeError):
        return None


def parse_spec_block(body: str | None) -> dict | None:
    """The (possibly reviewer-edited) spec block from a PR body, or None."""
    if not body:
        return None
    m = _SPEC_BLOCK_RE.search(body.replace("\r\n", "\n"))
    if not m:
        return None
    try:
        return json.loads(m.group(1))
    except json.JSONDecodeError:
        return None
